-- MySQL Script generated by MySQL Workbench
-- ter 17 set 2019 19:53:06 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eventosfatec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventosfatec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventosfatec` DEFAULT CHARACTER SET utf8mb4 ;
USE `eventosfatec` ;

-- -----------------------------------------------------
-- Table `eventosfatec`.`tipopessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`tipopessoa` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eventosfatec`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`escolaridade` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventosfatec`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`pessoa` (
  `cpfcnpj` VARCHAR(14) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `tipo_id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `observacao` TEXT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `escolaridade_id` INT NOT NULL,
  `cep` VARCHAR(10) NULL,
  `cidade` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `id_tipo` (`tipo_id` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpfcnpj` ASC),
  INDEX `fk_pessoa_escolaridade1_idx` (`escolaridade_id` ASC),
  CONSTRAINT `pessoa_idfk_1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `eventosfatec`.`tipopessoa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_pessoa_escolaridade1`
    FOREIGN KEY (`escolaridade_id`)
    REFERENCES `eventosfatec`.`escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- Table `eventosfatec`.`statusevento`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `eventosfatec`.`statusevento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `eventosfatec`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `datahora_inicio` DATETIME NOT NULL,
  `datahora_fim` DATETIME NOT NULL,
  `localizacao` VARCHAR(100) NOT NULL,
  `valor` FLOAT NOT NULL,
  `status_id` INT(11) NOT NULL,
  `pessoa_id` INT NOT NULL,
  `organizador_pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_status_id_idx` (`status_id` ASC),
  INDEX `fk_organizador_pessoa_id_idx` (`organizador_pessoa_id` ASC),
  INDEX `fk_evento_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_evento_pessoa2_idx` (`organizador_pessoa_id` ASC),
  CONSTRAINT `evento_ibfk_1`
    FOREIGN KEY (`status_id`)
    REFERENCES `eventosfatec`.`statusevento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evento_ibfk_2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `eventosfatec`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evento_ibfk_3`
    FOREIGN KEY (`organizador_pessoa_id`)
    REFERENCES `eventosfatec`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eventosfatec`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`categoria` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- Table `eventosfatec`.`entradaevento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`entradaevento` (
  `id` INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `datahora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT `FK_EVENTO`
    FOREIGN KEY (`evento_id`)
    REFERENCES `eventosfatec`.`evento`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	 CONSTRAINT `FK_PESSOA`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `eventosfatec`.`pessoa`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `eventosfatec`.`statusatividade`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `eventosfatec`.`statusatividade` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `eventosfatec`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`atividade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `evento_id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `datahora_inicio` DATETIME NOT NULL,
  `datahora_fim` DATETIME NOT NULL,
  `localizacao` VARCHAR(100) NULL DEFAULT NULL,
  `vagas` INT(11) NOT NULL,
  `horas` INT(11) NOT NULL,
  `status_id` INT(11) NOT NULL,
  `palestrante_pessoa_id` INT(11),
  PRIMARY KEY (`id`),
  INDEX `fk_status_id_idx` (`status_id` ASC),
  INDEX `fk_evento_id_idx` (`evento_id` ASC),
  INDEX `fk_categoria_id_idx` (`categoria_id` ASC),
  CONSTRAINT `atividade_ibfk_1`
    FOREIGN KEY (`status_id`)
    REFERENCES `eventosfatec`.`statusatividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `atividade_ibfk_2`
    FOREIGN KEY (`palestrante_pessoa_id`)
    REFERENCES `eventosfatec`.`pessoa` (`id`)
	 ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `atividade_ibfk_3`
    FOREIGN KEY (`evento_id`)
    REFERENCES `eventosfatec`.`evento` (`id`)
	 ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `atividade_ibfk_4`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `eventosfatec`.`categoria` (`id`)
	 ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `eventosfatec`.`statusinscricao`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `eventosfatec`.`statusinscricao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `eventosfatec`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`inscricao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `atividade_id` INT NOT NULL,
  `status_id` INT(11) NOT NULL,
  `sign_cert` VARCHAR(128) NULL DEFAULT NULL,
  `datahora_sign` TIMESTAMP(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_id_idx` (`pessoa_id` ASC),
  INDEX `fk_atividade_id_idx` (`atividade_id` ASC),
  CONSTRAINT `inscricao_ibfk_1`
    FOREIGN KEY (`status_id`)
    REFERENCES `eventosfatec`.`statusinscricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inscricao_ibfk_2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `eventosfatec`.`pessoa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `inscricao_ibfk_3`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `eventosfatec`.`atividade` (`id`)
	 ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4;


ALTER TABLE `inscricao` ADD COLUMN (datahora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP());

-- -----------------------------------------------------
-- Table `eventosfatec`.`pessoaimagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`pessoaimagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `pessoa_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventoimagens_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_eventoimagens_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `eventosfatec`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- Adicionar campo imagem a pessoa e fazer FK
-- -----------------------------------------------------

ALTER TABLE `eventosfatec`.`pessoa`
ADD COLUMN `pessoaimagens_id` INT(11) NULL;
ALTER TABLE pessoa
ADD FOREIGN KEY (pessoaimagens_id) REFERENCES pessoaimagens(id);

-- -----------------------------------------------------
-- Adicionar campo datahora_cadastro a pessoa
-- -----------------------------------------------------

ALTER TABLE `pessoa` ADD COLUMN (datahora_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP());

-- -----------------------------------------------------
-- Table `eventosfatec`.`eventoimagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventosfatec`.`eventoimagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `evento_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventoimagens_evento1_idx` (`evento_id` ASC),
  CONSTRAINT `fk_eventoimagens_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `eventosfatec`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table structure for table `eventosfatec`.`pais`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `eventosfatec`.`pais` (
  `paisId` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `paisNome` varchar(50) NOT NULL,
  `paisName` varchar(50) NOT NULL,
  PRIMARY KEY (`paisId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;

-- -----------------------------------------------------
-- Table structure for table `eventosfatec`.`sms`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `eventosfatec`.`sms` (id INT NOT NULL primary key AUTO_INCREMENT, 
						numero TEXT,
						msg TEXT,						
						ret_sendsms TEXT,
						datahora_send DATETIME,
						ret_statussms TEXT,
						datahora_status DATETIME,
						ret_consultasaldo TEXT )

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;